### ISSUE TITLE
Transfer of dsboger/zimsearch → achadwick/zimsearch

### ISSUE THREAD

**Issue by achadwick** [dsboger/zimsearch#10]
@dsboger 
Thanks for transferring ownership of this repository to me. It seems to be working correctly now, and I've inherited all the old issue reports too. I'm happy to look after your code for you, since I'm a regular user of this awesome plugin :smiley:

You still have commit access, and I intend to keep that open.

Just some legal/attribution questions for form's sake...

1. How do you want to continue to be attributed? Should I keep your email masked in AUTHORS and related documentation? I consider you the original author, want to keep you listed.

2. How do you want to be attributed in code? I intend to add myself there for new commits, and assign date ranges for the Ⓒ lines based on the commit log. Hope that's OK.

3. Is it your intent that the license is "GPLv2", or "GPLv2 or any later version"?

**Comment by dsboger-zz** [comment]
It is unlikely that I'll have something to add anymore to zimsearch, since the last I used Zim was more than a year ago. About the legal/attribution, I'm not too experienced/concerned about such matters:

1. That's fine.
2. OK for sure.
3. "GPLv2 or any later version".

**Comment by achadwick** [comment]
Thanks for confirming. Better to be certain about licensing things.
