### ISSUE TITLE
Linking to official plugins list of Zim

### ISSUE THREAD

**Issue by sojusnik** [dsboger/zimsearch#3]
It would be very helpful for new users (and the popularity of this plugin) to find your great plugin in the [official plugins list](https://github.com/jaap-karssenberg/zim-wiki/wiki/Plugins) of Zim on GitHub.

**Comment by sojusnik** [comment]
I've made a small entry regarding your plugin [here](https://github.com/jaap-karssenberg/zim-wiki/wiki/Plugins).

**Comment by dsboger-zz** [comment]
Thanks for that! I just pushed a new set of commits to github to improve a lot of things. So I updated the plugin description to match.
