### ISSUE TITLE
Improve readability

### ISSUE THREAD

**Issue by sojusnik** [dsboger/zimsearch#4]
If "search all notebooks, instead of only the default" is disabled in the plugin's settings, then the notebook name in the Gnome Shell overview (marked with an "#") should be hidden. This would make the results easier to read.

**Comment by achadwick** [comment]
Minimal PR attached ☺

Hmm. Is it just me, or are #notebook terms still respected even if only searching the default notebook? Hopefully, even if they are, it won't screw up filtering of results - I've not really checked.
