### ISSUE TITLE
Needs better documentation and easier install steps (was: How I can use it on Xubuntu ?)

### ISSUE THREAD

**Issue by Nick222** [dsboger/zimsearch#8]
Can I use it on Xubuntu 17/04-64 (and how) or not ?

**Comment by achadwick** [comment]
Hi there. What version of Zim are you using, please?

(I may be taking over the zimsearch project soon if @dsboger allows. I know that it works with Debian testing's zim 0.65, but we've been having reports of trouble with zim 0.66 on Ubuntu in #2)

**Comment by Nick222** [comment]
python2 ./setup.py --dry-run install

running install
running build
running build_scripts
creating build
creating build/scripts-2.7
copying and adjusting zim-gnomeshellsearch -> build/scripts-2.7
changing mode of build/scripts-2.7/zim-gnomeshellsearch
running install_scripts
running install_data
creating /usr/local/share/zim
creating /usr/local/share/zim/plugins
error: can't copy 'src/gnomeshellsearch.py': doesn't exist or not a regular file

**Comment by Nick222** [comment]
OK - download src/gnomeshellsearch.py

python2 ./setup.py --dry-run install

running install
running build
running build_scripts
creating build
creating build/scripts-2.7
copying and adjusting zim-gnomeshellsearch -> build/scripts-2.7
changing mode of build/scripts-2.7/zim-gnomeshellsearch
running install_scripts
running install_data
creating /usr/local/share/zim
creating /usr/local/share/zim/plugins
copying src/gnomeshellsearch.py -> /usr/local/share/zim/plugins
creating /usr/local/share/dbus-1
creating /usr/local/share/dbus-1/services
expanding data/zim.plugins.gnomeshellsearch.provider.service.in -> /usr/local/share/dbus-1/services/zim.plugins.gnomeshellsearch.provider.service
creating /usr/local/share/gnome-shell
creating /usr/local/share/gnome-shell/search-providers
expanding data/zim.plugins.gnomeshellsearch.provider.ini.in -> /usr/local/share/gnome-shell/search-providers/zim.plugins.gnomeshellsearch.provider.ini
running install_egg_info
Writing /usr/local/lib/python2.7/dist-packages/zimsearch-0.0.0.egg-info

But:

sudo python2 ./setup.py install

running install
running build
running build_scripts
running install_scripts
copying build/scripts-2.7/zim-gnomeshellsearch -> /usr/local/bin
changing mode of /usr/local/bin/zim-gnomeshellsearch to 775
running install_data
creating /usr/local/share/zim
creating /usr/local/share/zim/plugins
copying src/gnomeshellsearch.py -> /usr/local/share/zim/plugins
creating /usr/local/share/dbus-1
creating /usr/local/share/dbus-1/services
expanding data/zim.plugins.gnomeshellsearch.provider.service.in -> /usr/local/share/dbus-1/services/zim.plugins.gnomeshellsearch.provider.service
error: [Errno 2] No such file or directory: 'data/zim.plugins.gnomeshellsearch.provider.service.in'

**Comment by achadwick** [comment]
Something looks very wrong with your local coy of the repository. Does [data/zim.plugins.gnomeshellsearch.provider.service.in](https://github.com/dsboger/zimsearch/blob/master/data/zim.plugins.gnomeshellsearch.provider.service.in) not exist in it?

**Comment by achadwick** [comment]
@Nick222 
What version of Zim are you using, please?

**Comment by Nick222** [comment]
I am stupid :(
Now all OK (I did not download data-folder...)
Zim 0.66

But how can I use it?
I must install gnome-shell-search and Nautilus? (I did it)
It search from inside Zim or from gnome-shell-search or Nautilus ?

Excuse me - I cannot understand...

**Comment by achadwick** [comment]
It's OK. The documentation could be improved a lot! Screenshots in the README, maybe. Step-by-step installation instructions, definitely.

Thanks for the information about versions. I haven't tested with Zim 0.66 yet.

Zimsearch runs in GNOME, in gnome-shell's Activities and search "overlay". You need to install Zim and gnome-shell. It does not search from inside Zim. It does not search from inside Nautilus.

You may want to wait a bit and watch the project for new commits and update: I'm intending to make it pip-installable from source fairly soon, which will be more more convenient and allow uninstallation.

The best way to maintain your installation at this stage in development is to use `git`. Don't rely on manually copied folders, use the right tool for the job.

Note that, the repository location might be about to change quite soon. I don't want to give out instructions which will soon be obsolete.

**Comment by Nick222** [comment]
But Xubuntu use XFCE - not GNOME

Is it mean that I cannot use it without GNOME (with gnome-shell-search only)?

**Comment by achadwick** [comment]
I should have seen that earlier! Oh, now I feel foolish :flushed: 

I think you would have to install GNOME to use this on your Xubuntu installation. Sorry about that.

If you're still interested, please flip this issue back to "Open" and I'll take another look. Good luck.

**Comment by Nick222** [comment]
I still interested but how I can flip this issue back to "Open" ?
Or I must create new issue (question) ?

**Comment by achadwick** [comment]
Okay, but all I can do is improve the zimsearch documentation and make it easier to install. This is not a general Xubuntu support forum.

**Comment by achadwick** [comment]
Okay, I've updated the documentation to make it clearer that this is for GNOME desktops. I've improved the install steps too.

One thing I *can* recommend for Xubuntu is the [Kupfer](https://kupferlauncher.github.io/) application launcher. I lived in it for ages in Xfce before migrating to GNOME, and I recall it being rather awesome and having a Zim plugin.

Good luck!
